[package]
name = "magma"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.36.0"
log = "0.4.14"
winit = "0.26.1"
cgmath = "0.18.0"
image = "0.24.1"
memoffset = "0.6.5"
tobj = "3.2.1"
thiserror = "1.0.30"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["windef", "libloaderapi"] }

[dev-dependencies]
simple_logger = "2.1.0"
anyhow = "1.0.56"
