[package]
name = "magma_derive"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.16"
syn = { version = "1.0.89", features = ["parsing", "derive", "extra-traits"] }
proc-macro2 = "1.0.36"
darling = "0.13.1"

[lib]
proc-macro = true