[package]
name = "magma_render"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.36.0"
winit = "0.26.1"
log = "0.4.14"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["windef", "libloaderapi"] }
